apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-account
  namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-token: "true"
    spec:
      serviceAccountName: app-account
      containers:
      - name: app
        image: vault-demo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault:8200"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-demo-app
  namespace: app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: vault-demo
